/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Mathias
 */
public class Interfaz2 extends javax.swing.JFrame {

    public ImageIcon imagen;
    public Icon icono;
    DefaultTableModel modelo;

    public Interfaz2() {
        initComponents();
        this.setLocationRelativeTo(null);

        modelo = new DefaultTableModel();
        modelo.addColumn("Código");
        modelo.addColumn("UD.");
        modelo.addColumn("Nombre");
        modelo.addColumn("Talla");
        modelo.addColumn("Metros tela");
        this.tabla.setModel(modelo);
        jLabelResto.setOpaque(true);
        setIconImage(getIconImage());
    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/cortadora.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelcontrolcortes = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelUd = new javax.swing.JLabel();
        jTextFieldUd = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldRollo = new javax.swing.JTextField();
        jLabelRollo = new javax.swing.JLabel();
        jButtonEliminar = new javax.swing.JButton();
        jButtonAgregar = new javax.swing.JButton();
        JScrollPanel = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTalla = new javax.swing.JTextField();
        jLabelTalla = new javax.swing.JLabel();
        jLabelMetros = new javax.swing.JLabel();
        jTextFieldMetros = new javax.swing.JTextField();
        jLabelResto = new javax.swing.JLabel();
        jTextFieldResto = new javax.swing.JTextField();
        jButtonEnviar = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1345, 750));
        setMinimumSize(new java.awt.Dimension(880, 410));
        setPreferredSize(new java.awt.Dimension(1345, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelcontrolcortes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelcontrolcortes.setText("CONTROL DE CORTES");
        getContentPane().add(jLabelcontrolcortes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, 50));

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 20, 180, 130));

        jLabelCodigo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCodigo.setText("Código : ");
        getContentPane().add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jTextFieldCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 90, 30));

        jLabelUd.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelUd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUd.setText("UD : ");
        getContentPane().add(jLabelUd, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jTextFieldUd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUdActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldUd, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 90, 30));

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNombre.setText("Nombre:");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jTextFieldRollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRolloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 90, 30));

        jLabelRollo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelRollo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRollo.setText("Rollo:");
        getContentPane().add(jLabelRollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 170, -1, -1));

        jButtonEliminar.setBackground(new java.awt.Color(0, 195, 225));
        jButtonEliminar.setForeground(new java.awt.Color(255, 51, 51));
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, -1, -1));

        jButtonAgregar.setBackground(new java.awt.Color(0, 195, 225));
        jButtonAgregar.setForeground(new java.awt.Color(0, 102, 51));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 230, -1, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPanel.setViewportView(tabla);

        getContentPane().add(JScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 690, -1));

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 90, 30));

        jTextFieldTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTallaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 170, 90, 30));

        jLabelTalla.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTalla.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTalla.setText("Talla:");
        getContentPane().add(jLabelTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, -1, -1));

        jLabelMetros.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelMetros.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMetros.setText("Metros:");
        getContentPane().add(jLabelMetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, -1, -1));

        jTextFieldMetros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMetrosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMetros, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, 90, 30));

        jLabelResto.setBackground(new java.awt.Color(0, 195, 225));
        jLabelResto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelResto.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResto.setText("Resto");
        jLabelResto.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(jLabelResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, 60, -1));

        jTextFieldResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRestoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldResto, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 90, 30));

        jButtonEnviar.setBackground(new java.awt.Color(0, 195, 225));
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setText("Enviar");
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 450, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo x2.jpg"))); // NOI18N
        jLabelFondo.setMaximumSize(new java.awt.Dimension(1345, 750));
        jLabelFondo.setMinimumSize(new java.awt.Dimension(880, 410));
        jLabelFondo.setPreferredSize(new java.awt.Dimension(1345, 750));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-16, -20, 1345, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoActionPerformed

    private void jTextFieldUdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUdActionPerformed

    private void jTextFieldRolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRolloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRolloActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        if (tabla.getSelectedRow() >= 0) {
            int respuesta = JOptionPane.showConfirmDialog(this, "Desea eliminar el registro", "Sistema", JOptionPane.INFORMATION_MESSAGE);

            if (respuesta == JOptionPane.YES_OPTION) {
                modelo.removeRow(tabla.getSelectedRow());
                calcularResto();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecciona una fila");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String[] datos = new String[5];

        if (tabla.getRootPane() != null) {
            datos[0] = jTextFieldCodigo.getText();
            datos[1] = jTextFieldUd.getText();
            datos[2] = jTextFieldNombre.getText();
            datos[3] = jTextFieldTalla.getText();
            datos[4] = jTextFieldMetros.getText();

            modelo.addRow(datos);
            calcularResto();
            tabla.setModel(modelo);

        }


    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTallaActionPerformed

    private void jTextFieldMetrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMetrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMetrosActionPerformed

    private void jTextFieldRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRestoActionPerformed


    }//GEN-LAST:event_jTextFieldRestoActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed

        double resto = Double.parseDouble(String.valueOf(jTextFieldResto.getText()));
        if (resto < 0) {
            JOptionPane.showMessageDialog(this, "No se puede enviar a cortadora");
        } else {
            JOptionPane.showMessageDialog(this, "Enviado a cortadora");
            modelo.getDataVector().removeAllElements();
            jTextFieldCodigo.setText("");
            jTextFieldUd.setText("");
            jTextFieldNombre.setText("");
            jTextFieldRollo.setText("");
            jTextFieldTalla.setText("");
            jTextFieldMetros.setText("");
            tabla.updateUI();
        }


    }//GEN-LAST:event_jButtonEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz2().setVisible(true);
        });

    }

    public void calcularResto() {
        DecimalFormat formato = new DecimalFormat();
        formato.setMaximumFractionDigits(2);
        double resto = Double.parseDouble(jTextFieldRollo.getText());
        double fila;

        for (int i = 0; i < tabla.getRowCount(); i++) {

            fila = Double.parseDouble(tabla.getValueAt(i, 4).toString());
            double unidades = Double.parseDouble(tabla.getValueAt(i, 1).toString());

            resto -= fila * unidades;

            if (resto < 0) {
                JOptionPane.showMessageDialog(this, "No se pueden agregar más prendas");

            }
        }
        jTextFieldResto.setText(String.valueOf(formato.format(resto)));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPanel;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMetros;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelResto;
    private javax.swing.JLabel jLabelRollo;
    private javax.swing.JLabel jLabelTalla;
    private javax.swing.JLabel jLabelUd;
    private javax.swing.JLabel jLabelcontrolcortes;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldMetros;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldResto;
    private javax.swing.JTextField jTextFieldRollo;
    private javax.swing.JTextField jTextFieldTalla;
    private javax.swing.JTextField jTextFieldUd;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

}
